import '@/ui/global.css';
import { inter } from '@/ui/fonts';
import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';
import type { Metadata } from 'next';
import { ReactNode, Suspense } from 'react';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: {
  children: ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <Suspense>
          {/* <Navbar /> */}
          {children}
          {/* <Footer /> */}
        </Suspense>
      </body>
    </html>
  );
}